pandoc.exe test.docx --to markdown -o "exp/test_markdown.md" --wrap=none --extract-media="exp/markdown"
pandoc.exe test.docx --to commonmark -o "exp/test_commonmark.md" --wrap=none --extract-media="exp/commonmark"
pandoc.exe test.docx --to commonmark_x -o "exp/test_commonmark_x.md" --wrap=none --extract-media="exp/commonmark_x"
pandoc.exe test.docx --to gfm -o "exp/test_gfm.md" --wrap=none --extract-media="exp/gfm"
pandoc.exe test.docx --to gfm+bracketed_spans+raw_attribute+subscript-raw_html -o "exp/test_gfm2.md" --wrap=none --extract-media="exp/gfm2"
pandoc.exe test.docx --to markdown+mark+all_symbols_escapable -o "exp/test_markdown2.md" --wrap=none --extract-media="exp/markdown2"
pandoc.exe test.docx --to markdown_strict -o "exp/test_markdown_strict.md" --wrap=none --extract-media="exp/markdown_strict"
pandoc.exe test.docx --to markdown_strict+mark+emoji++all_symbols_escapable+grid_tables+markdown_attribute+pipe_tables+strikeout -o "exp/test_markdown_strict2.md" --wrap=none --extract-media="exp/markdown_strict2"pandoc.exe test.docx --to markdown_strict+emoji+gfm_auto_identifiers+grid_tables+markdown_attribute+multiline_tables+pipe_tables+simple_tables+strikeout -o "exp/test_markdown_strict2.md" --wrap=none --extract-media="exp/markdown_strict2"
pandoc.exe test.docx --to markdown_strict+emoji+gfm_auto_identifiers+grid_tables+markdown_attribute+multiline_tables+pipe_tables+simple_tables+strikeout -o "exp/test_markdown_strict2.md" --wrap=none --extract-media="exp/markdown_strict2"pandoc.exe test.docx --to markdown_strict+emoji+gfm_auto_identifiers+grid_tables+markdown_attribute+multiline_tables+pipe_tables+simple_tables+strikeout -o "exp/test_markdown_strict3.md" --wrap=none --extract-media="exp/markdown_strict2"
