<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Office.Interop.OneNote">
      <HintPath>..\OneNoteMdExporter\libs\Microsoft.Office.Interop.OneNote.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <!-- COMReference of OneNoteMdExporter not yet supported by DotNet5 -->
    <PackageReference Include="NUnit" Version="4.1.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <!-- DotNet3 do not include .deps and runtime file for project reference : https://github.com/dotnet/sdk/issues/1675  -->
    <ProjectReference Include="..\OneNoteMdExporter\OneNoteMdExporter.csproj" />
  </ItemGroup>

</Project>
