using alxnbl.OneNoteMdExporter.Models;
using System;
using System.Text.RegularExpressions;

namespace alxnbl.OneNoteMdExporter.Services.Export
{
    /// <summary>
    /// COM-free, pure string logic for building markdown attachment references and normalizing
    /// file names. Extracted from <see cref="ExportServiceBase"/> so it can be unit-tested without
    /// the COM-coupled base class (OneNote interop). Behaviour is unchanged - pure cut/paste.
    /// </summary>
    internal static class AttachmentReferenceHelper
    {
        /// <summary>
        /// Replace the tag &lt;&lt;FileName&gt;&gt; generated by OneNote by a markdown link referencing the attachment.
        /// </summary>
        internal static void InsertPageMdAttachmentReference(ref string pageMdFileContent, Attachement attach, Func<Attachement, string> getAttachMdReferenceMethod)
        {
            // Replace only the first still-open matching placeholder so that several attachments sharing the same
            // name on one page are each linked to their own file rather than all to the first one.
            var alreadyReplaced = false;

            // Note the lazy quantifier (.*?): a greedy .* would span across multiple consecutive \<\<...\>\> tags
            // on the same page, so the comparison below would never match and no link would be inserted.
            var pageMdFileContentModified = Regex.Replace(pageMdFileContent, "(\\\\<){2}(?<fileName>.*?)(\\\\>){2}", delegate (Match match)
            {
                if (alreadyReplaced)
                    return match.Value;

                var refFileName = match.Groups["fileName"]?.Value ?? "";
                // PanDoc escapes special characters (_, [, ], etc.) in markdown; remove the backslash escapes before comparing
                var refFileNameUnescaped = Regex.Replace(refFileName, @"\\(.)", "$1");
                // Normalize invisible/space variants on both sides so the comparison matches the (already normalized) preferred name
                refFileNameUnescaped = RemoveInvisibleChars(refFileNameUnescaped);
                var attachOriginalFileName = attach.OneNotePreferredFileName;
                var attachMdRef = getAttachMdReferenceMethod(attach);

                if (refFileNameUnescaped.Equals(attachOriginalFileName))
                {
                    // reference found is corresponding to the attachment being processed
                    alreadyReplaced = true;
                    // Link target: wrap in angle brackets <...> so any valid Windows file name (commas, '+', spaces,
                    // umlauts, ...) resolves literally without percent-encoding, which Obsidian mis-decodes. Angle
                    // brackets only forbid '<' '>' newline - all illegal in Windows file names anyway.
                    // Label: replace '[' / ']' with round brackets - square brackets break the markdown link in
                    // Obsidian whether escaped ("\[") or literal ("["); only a bracket-free label resolves.
                    var label = attachOriginalFileName.Replace("[", "(").Replace("]", ")");
                    return $"[{label}](<{attachMdRef}>)";
                }
                else
                {
                    // not the current attachment, ignore
                    return match.Value;
                }
            });

            pageMdFileContent = pageMdFileContentModified;
        }

        /// <summary>
        /// Normalize OneNote file names for comparison: replace no-break/narrow spaces (U+00A0/2007/202F) with a
        /// normal space and strip invisible formatting characters (soft hyphen, zero-width spaces, word joiner, BOM).
        /// OneNote keeps these in a file name but PanDoc strips/normalizes them in the &lt;&lt;name&gt;&gt; tag, which
        /// would otherwise make the attachment file name and the markdown link differ by an (invisible) character and
        /// break the link.
        /// </summary>
        internal static string RemoveInvisibleChars(string s)
        {
            if (s == null) return null;
            s = Regex.Replace(s, "[\u00A0\u2007\u202F]", " ");
            return Regex.Replace(s, "[\u00AD\u200B\u200C\u200D\u2060\uFEFF]", "");
        }
    }
}
